using tokenType = char;
const tokenType TT_AT = '@';
const tokenType TT_HH = '#';
const tokenType TT_LP = '(';
const tokenType TT_RP = ')';
const tokenType TT_LT = '<';
const tokenType TT_GT = '>';
const tokenType TT_DH = '-';
const tokenType TT_QT = '"';
const tokenType TT_LB = '{';
const tokenType TT_RB = '}';
const tokenType TT_QQ = '?';
const tokenType TT_EX = '!';
const tokenType TT_CL = ':';
const tokenType TT_SC = ';';
const tokenType TT_SB = '[';
const tokenType TT_EB = ']';
const tokenType TT_EQ = '=';
